CONTIKI_PROJECT = udp-client udp-server
all: $(CONTIKI_PROJECT)

CONTIKI=../../..
include $(CONTIKI)/Makefile.include

include $(CONTIKI)/Makefile.dir-variables

MODULES += os/services/simple-energest
